
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author andet
 */
public class VtnGrafos extends javax.swing.JFrame {
    
    Grafo grafo = new Grafo();
    
    /**
     * Creates new form VtnGrafos
     */
    public VtnGrafos() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(605,500);
        cmbV.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMA = new javax.swing.JButton();
        btnAA = new javax.swing.JButton();
        btnLA = new javax.swing.JButton();
        btnEA = new javax.swing.JButton();
        lbl4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        txtVertice = new javax.swing.JTextField();
        btnAV = new javax.swing.JButton();
        btnEV = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        cmbDe = new javax.swing.JComboBox<>();
        lbl3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrarVA = new javax.swing.JTextArea();
        cmbHasta = new javax.swing.JComboBox<>();
        lbl5 = new javax.swing.JLabel();
        btnMV = new javax.swing.JButton();
        cmbV = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnMA.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnMA.setText("Ver matriz adyacencia");
        btnMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAActionPerformed(evt);
            }
        });
        getContentPane().add(btnMA);
        btnMA.setBounds(30, 190, 260, 31);

        btnAA.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnAA.setText("Agregar");
        btnAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAAActionPerformed(evt);
            }
        });
        getContentPane().add(btnAA);
        btnAA.setBounds(30, 150, 120, 31);

        btnLA.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnLA.setText("Ver lista adyacencia");
        btnLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLAActionPerformed(evt);
            }
        });
        getContentPane().add(btnLA);
        btnLA.setBounds(310, 190, 199, 31);

        btnEA.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnEA.setText("Eliminar");
        btnEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEAActionPerformed(evt);
            }
        });
        getContentPane().add(btnEA);
        btnEA.setBounds(200, 150, 110, 31);

        lbl4.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        lbl4.setText("ARISTAS");
        getContentPane().add(lbl4);
        lbl4.setBounds(20, 80, 80, 23);

        lbl1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        lbl1.setText("Insertar dato");
        getContentPane().add(lbl1);
        lbl1.setBounds(20, 40, 107, 23);

        txtVertice.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        getContentPane().add(txtVertice);
        txtVertice.setBounds(150, 40, 130, 30);

        btnAV.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnAV.setText("Agregar");
        btnAV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAVActionPerformed(evt);
            }
        });
        getContentPane().add(btnAV);
        btnAV.setBounds(300, 40, 100, 31);

        btnEV.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnEV.setText("Eliminar");
        btnEV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEVActionPerformed(evt);
            }
        });
        getContentPane().add(btnEV);
        btnEV.setBounds(410, 40, 100, 31);

        lbl2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        lbl2.setText("Desde");
        getContentPane().add(lbl2);
        lbl2.setBounds(20, 110, 60, 23);

        cmbDe.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        getContentPane().add(cmbDe);
        cmbDe.setBounds(90, 110, 75, 29);

        lbl3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        lbl3.setText("Hasta");
        getContentPane().add(lbl3);
        lbl3.setBounds(200, 110, 50, 23);

        txtMostrarVA.setColumns(20);
        txtMostrarVA.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        txtMostrarVA.setRows(5);
        jScrollPane1.setViewportView(txtMostrarVA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 239, 540, 220);

        cmbHasta.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        getContentPane().add(cmbHasta);
        cmbHasta.setBounds(260, 110, 90, 29);

        lbl5.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        lbl5.setText("VÉRTICES");
        getContentPane().add(lbl5);
        lbl5.setBounds(20, 10, 90, 23);

        btnMV.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnMV.setText("Mostrar Vértices");
        btnMV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMVActionPerformed(evt);
            }
        });
        getContentPane().add(btnMV);
        btnMV.setBounds(400, 100, 170, 31);

        cmbV.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        getContentPane().add(cmbV);
        cmbV.setBounds(400, 130, 170, 29);

        lblFondo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pas (1).jpg"))); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 610, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAActionPerformed
       boolean m[][] = grafo.matrizAd();
       String es = "   ";
       for(int a = 0; a < cmbV.getItemCount(); a++){
           es += cmbV.getItemAt(a) + " ";
       }
       for(int a = 0; a < cmbV.getItemCount(); a++){
           es += "\n" + cmbV.getItemAt(a) + " ";
           for (int b = 0; b < cmbV.getItemCount(); b++) {
                es += m[a][b] ? "1 " : "0 ";
            }
       }
       txtMostrarVA.setText(es);
    }//GEN-LAST:event_btnMAActionPerformed

    private void btnAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAAActionPerformed
        grafo.insertarArista((char)cmbDe.getSelectedItem(),(char)cmbHasta.getSelectedItem());
    }//GEN-LAST:event_btnAAActionPerformed

    private void btnLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLAActionPerformed
        if(cmbV.getItemCount() > 0)txtMostrarVA.setText(grafo.listaAd((char)cmbV.getSelectedItem()));
    }//GEN-LAST:event_btnLAActionPerformed

    private void btnEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEAActionPerformed
        grafo.eliminarArista((char)cmbDe.getSelectedItem(),(char)cmbHasta.getSelectedItem());
    }//GEN-LAST:event_btnEAActionPerformed

    private void btnAVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAVActionPerformed
        try{
        char v =  txtVertice.getText().toUpperCase().charAt(0);
        if(grafo.insertarVertice(v)){
            cmbDe.addItem(v);
            cmbV.addItem(v);
            cmbHasta.addItem(v);
        }txtVertice.setText("");
        }catch(StringIndexOutOfBoundsException e){
            showMessageDialog(null,"Inserta un dato");
            txtVertice.requestFocus();
        }
    }//GEN-LAST:event_btnAVActionPerformed

    private void btnEVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEVActionPerformed
        try{
        char v =  (char)cmbV.getSelectedItem();
        if(grafo.eliminarVertice(v)){
            cmbDe.removeItem(v);
            cmbV.removeItem(v);
            cmbHasta.removeItem(v);
            return;
        }
        }catch(NullPointerException n){
            showMessageDialog(null,"Error, NO hay vértices a eliminar");
            txtVertice.requestFocus();
        }
    }//GEN-LAST:event_btnEVActionPerformed

    private void btnMVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMVActionPerformed
        cmbV.setVisible(true);
    }//GEN-LAST:event_btnMVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnGrafos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnGrafos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAA;
    private javax.swing.JButton btnAV;
    private javax.swing.JButton btnEA;
    private javax.swing.JButton btnEV;
    private javax.swing.JButton btnLA;
    private javax.swing.JButton btnMA;
    private javax.swing.JButton btnMV;
    private javax.swing.JComboBox<Character> cmbDe;
    private javax.swing.JComboBox<Character> cmbHasta;
    private javax.swing.JComboBox<Character> cmbV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextArea txtMostrarVA;
    private javax.swing.JTextField txtVertice;
    // End of variables declaration//GEN-END:variables
}
